Lang: "en"

#Need for users, using paper 1.16+. Paper has problem with Chat Packets because of which users who use paper has problems
ChatFormatEnable: false
ChatFormat: "<{player}> {message}"

#MYSQL; LOCAL
StorageType: local
mysql:
  host: 'localhost'
  port: 3306
  user: 'root'
  pass: ''
  database: 'censure'

#Minimal word lenght for censure
MinWordLenght: 3
#Maximum word lenght for censure
MaxWordLenght: 6

DefaultEnableCensure: true

RandomCharsEnable: true
RandomChars:
  - '*'
  - "%"
  - "$"
  - "#"
  - "@"
  - '•'
  - '∆'
#Character to replace censored words
CensureChar: "*"
#Shows the original post form when hovering over the text
HoverEnable: true