StorageType: mysql #MYSQL; YML
mysql:
  host: 'localhost'
  port: 3306
  user: 'root'
  pass: ''
  database: 'censure'

MinWordLenght: 3
MaxWordLenght: 6

CensuredWords:
  - "хуй"
  - "соси"

RemovedWords:
  - "оскорблять"
  - "корабля"

CensureChar: '*'
HoverEnable: true #Показывает исходную форму сообщения при наведении на текст

WordLenghtLimit: "§cСлово не должно быть меньше 3 и не больше 6 символов!"
HelpMessage: ""
WordNotCensured: "§cДанное слово не в цензуре"
WordAlredyCensured: "§cДанное слово уже в цензуре"
NoPermMessage: "§cУ вас недостаточно прав!"
ToggleMessage: "§fЦензура {action}"
AddedMessage: "§fСлово {word} успешно добавлено в цензуру"
RemovedMessage: "§fСлово {word} успешно удалено из цензуры"