Lang: "eng"

StorageType: mysql #MYSQL; YML
mysql:
  host: 'localhost'
  port: 3306
  user: 'root'
  pass: ''
  database: 'censure'

MinWordLenght: 3
MaxWordLenght: 6

MentionsEnable: true
DefaultEnableMentions: true #Initially, mentions work for all players.

CensureChar: '*'
HoverEnable: true #Shows the original post form when hovering over the text